const translations = {
    en: {
        //header
        home: 'Home',
        service: 'Service',
        about: 'About US',
        contact: 'Contact Us',
        FreeLegalAdvice:'Free Legal Advice',

        
        // Service
        LegalConsultations:"Legal Consultations",
        legalDocuments:"Preparation and drafting of legal documents",
        LegalProcedures:"Legal procedures, registration legal credits",
        LegalRepresentation:"Legal Representation",
        ResearchServices:"Research services",
        PenalCases:"Penal cases",
        CriminalCases:"Criminal Cases",
        CybercrimeLawsuit:"Cybercrime Lawsuit",
        LaborLawsuit:"Labor Lawsuit",
        RentDisputes:"Rent Disputes",
        FamilyIssuesAndConditions:"Family issues and conditions",
        Insurance:"Insurance",
        MaritimeDisputes:"Maritime disputes",
        BankingAndFinance:"Banking and Finance",
        TradingCompanies:"Trading companies",
        LitigationAndDisputeResolution:"Litigation And Dispute Resolution",
        PrecautionaryMeasures:"Precautionary measures",
        ExecutiveActions:"Executive Actions",
        RealEstateDisputes:"Real estate disputes",
        DebtCollection:"Debt Collection",

        // Legal Consultations
        Saleh_Al_Saleh_Legal_Consultations:"Saleh Al Saleh Advocates and Legal Consultants",
        SalehAlSalehLegalConsultationsB1:"Provides legal advice through a distinguished selection of legal advisors. It is characterized by an office that keeps pace with today's development s and techniques. Inthis accelerating era, every human being needs to know his or her rights, duties andlegal attitude towards an order, or a project submitted to him, with great speed andprecision. We therefore took care of this, and we did not confine ourselves totraditional ways of communicating betweenthe Office and its clients eager to take legal advice on a subject. Traditionally, anyclient with legal advice must go to thelaw firm specializing in it. At Saleh Al Saleh Law Firm and Legal Consulting, it isdifferent where you can send legal advice to us through email,Explaining all the details relating to them, one of the Bureau's specialized adviserswill consult them and give their legal opinion,supported by the texts of the law, and then send them to you by e-mail or fax, takinginto account the confidentiality of all the data and informationcontained in the consultation.We therefore took care of this, and we did not confineourselves to traditional ways of communicating betweenthe Office and its clients eager to take legal advice on a subject. Traditionally, anyclient with legal advice must go to thelaw firm specializing in it. At Saleh Al Saleh Law Firm and Legal Consulting, it isdifferent where you can send legal advice to us through email,Explaining all the details relating to them, one of the Bureau's specialized adviserswill consult them and give their legal opinion,supported by the texts of the law, and then send them to you by e-mail or fax, takinginto account the confidentiality of all the data and informationcontained in the consultation",
        Saleh_Al_Saleh_Legal_ConsultationsB2:"As legal consulting plays an important and effective role in guiding and advising clients before commencing legal proceedings, the office has been interested in providing the best services to clients through the legal consulting service provided by aspecialized team Who provides legal advice through qualified consultants, withdistinguished and specialized scientific and expert ammunition and through the latesttechnology whether on phone, internet, email, fax and SMS. The Legal Consulting Servicerequires the prompt provision of advice to enable the respondent to make decisionsquickly and accurately.",
        Saleh_Al_Saleh_Legal_ConsultationsB3:"provides consultations in Arabic and English in all legal aspects that meet individuals and companies their daily lives or in investments and business matters by providing legal advice and advice on the appropriate action to protect the client's interests ineach problem to ensure that the client has an understanding of his problem and itsconsequences and the actions to be taken to resolve the problem in order to avoidserious consequences.",
        Saleh_Al_Saleh_Legal_ConsultationsB4:"provides legal advice whether by arranging a meeting date with the competent lawyer and legal advisor responsible for the office or through electronic correspondence or telephone confirmation. The Office provides legal advice in writing and covered by legalrights of law, court practices and interpretations of jurists to indicate the sound bondto assure the client of the validity of the legal advice and its support.",
        Saleh_Al_Saleh_Legal_ConsultationsB5:"is linked to several annual consultancy contracts with commercial companies and financial institutions that wish to receive continuous services throughout the year whether with a lump-sum contract with a fixed or indefinite number of hours or undercontracts according to the working hours of consultants, legal researchers and lawyersto ensure the diversity of choices for clients.",
        Saleh_Al_Saleh_Legal_ConsultationsB6:"is a source of trust because the legal consultations issued by Al Saleh Law Firm are always accompanied by evidence, source and comprehensive statement adequate to first understand the client in order to ensure that he is assured of the soundness of the grounds on which the legal consultation was issued.",
        Lookingforlegaladvice:"Looking for legal advice? Contact us, and we'll start productive cooperation.",
        
       // Preparation and drafting of legal documents
        Preparation_legal_documentsB:"is the most famous office in the preparation and legal drafting in the UAE where we have a specialized team of legal advisers and researchers with expertise in the preparation and drafting of legal editions and documents of various forms and types The Office provides preparation and drafting services in Arabic and English. This includes all the implementation of companies and institutions with limited responsibility, private and public contributions, entrepreneurship and individuals as examples of such services towards the formulation and liberalization of",
        Preparation_legal_documents1:"Memorandum of Association and Their Annexes",
        Preparation_legal_documents2:"Mergers and acquisitions contract and agreement",
        Preparation_legal_documents3:"Commercial agency contracts",
        Preparation_legal_documents4:"Arbitration agreements",
        Preparation_legal_documents5:"Trade Sponsorship Contracts and Agreements",
        Preparation_legal_documents6:"Endowment and Will Contracts",
        Preparation_legal_documents7:"Mortgage contract",
        Preparation_legal_documents8:"Concession contracts",
        Preparation_legal_documents9:"Employment contracts",
        Preparation_legal_documents10:"Reconciliation agreements",
        Preparation_legal_documents11:"Marketing contracts",
        Preparation_legal_documents12:"Influencers and Influences Management Agreement",
        Preparation_legal_documents13:"Memorandums of Understanding",
        Preparation_legal_documents14:"Liquidation Minutes",
        Preparation_legal_documents15:"Publicity Minutes",
        Preparation_legal_documents16:"Affidavits Oaths",
        Preparation_legal_documents17:"Authorization Letter",
        Preparation_legal_documents18:"Internal Disciplinary Regulations",
        Preparation_legal_documents19:"Legal opinion memorandum",
        Preparation_legal_documents20:"Regulatory terms and conditions",
        Preparation_legal_documents21:"Drafting of opinion memorandum and legal advice",
        Preparation_legal_documents22:"Legal Correspondence",
        Preparation_legal_documents23:"Formulation of complaints and suggestions",
        Preparation_legal_documents24:"Writing legal correspondence",
        Preparation_legal_documents25:"Partnership contracts and agreements",
        Preparation_legal_documents26:"Shareholders' contract",
        Preparation_legal_documents27:"Confidentiality of information Agreements",
        Preparation_legal_documents28:"Trademark contracts",
        Preparation_legal_documents29:"Real estate rights contracts",
        Preparation_legal_documents30:"Loan contracts",
        Preparation_legal_documents31:"Waiver Contracts",
        Preparation_legal_documents32:"Lease contracts",
        Preparation_legal_documents33:"Settlement agreements",
        Preparation_legal_documents34:"Contracting contracts",
        Preparation_legal_documents35:"Logistics Services contracts",
        Preparation_legal_documents36:"Terms and Conditions",
        Preparation_legal_documents37:"Minutes of ordinary and extraordinary public associations of all companies",
        Preparation_legal_documents38:"Bankruptcy Minutes",
        Preparation_legal_documents39:"Meetings Minutes",
        Preparation_legal_documents40:"Private & General Power of Attorney",
        Preparation_legal_documents41:"Organizational regulations and corporate regulations",
        Preparation_legal_documents42:"Various legal notes",
        Preparation_legal_documents43:"Audit  legal documents",
        Preparation_legal_documents44:"Legal review and analysis of contracts and conventions",
        Preparation_legal_documents45:"Legal warnings",
        Preparation_legal_documents46:"Drafting legal warnings",
        Preparation_legal_documents47:"Writing various legal note",
        
        //Legal procedures, registration and legal credits
        LegalProcedures:"Legal procedures, registration and legal credits",
        LegalProceduresB:"offers legal procedures, registration and legal credits in the United Arab Emirates where we have a specialized team of lawyers and legal assistants with expertise in conducting procedures in various fields and various governmental and private works including all legal enforcement. Examples of such services are:",
        LegalProceduresB1:"Registration of companies and institutions with limited liability",
        LegalProceduresB2:"Corporate Registration and entrepreneurship",
        LegalProceduresB3:"Trademarks",
        LegalProceduresB4:"Insolvency",
        LegalProceduresB5:"Registration of private and public joint stock companies",
        LegalProceduresB6:"Intellectual property registration",
        LegalProceduresB7:"Liquidation",
        LegalProceduresB8:"Bankruptcy",
        LegalProceduresB9:"- Change: towards change of trade name, change of activity, change of management items Change of capital, change of company's duration or other terms of contract change one or more of the objectives of the Service's partnership with partners, Significant change in the organizational structure of the Service or partners affecting the management and status of the partnership Change in the structure of common services between the Service and partners, change one or more of the objectives of the Service's partnership with partners s organizational structure or partners affecting the management and status of the partnership concluded, Review the current partnership contract and submit a report to senior management indicating the scope of the partnership's change to negotiate with partners the objectives or services to be changed or added to the partnership contract, Adjustment and change according to lower quality of services provided through partners to amend or amend government legislation and laws in contravention of pre-concluded partnership agreements; Prepare the amended partnership contract in coordination with the Department of Legal Affairs, sign the amended partnership contract and cover the event informatively if the amendment is material and affects the clients; Establishment of a joint group to implement the amended provisions of the Convention, and of a joint group to implement the amended provisions of the Convention.",
        LegalProceduresB10:"Inventory of legacies",
        LegalProceduresB11:"Proof of mental ability and eligibility",
        LegalProceduresB12:"The guardian's personal information (supported by his passport)",
        LegalProceduresB13:"Whether another will relates to the testator's property and place of registration and if she wishes to cancel it",
        LegalProceduresB14:"Bank account details",
        LegalProceduresB15:"Proof of religion",
        LegalProceduresB16:"The elements needed to write the will",
        LegalProceduresB17:"Family tree (family members and their guardian's dependents)",
        LegalProceduresB18:"Property details are supported by copies of title deeds",
        LegalProceduresB19:"Details of any other property",
        
        
        // body
        Saleh_Al_Saleh: "Saleh Al Saleh Law Firm and Legal Consulting",
        body_index:"Saleh Al Saleh Law Firm and Legal Consulting is one of the most prominent legal services providers in the UAE through legal expertise and in professional ways, ensuring transactional satisfaction from any legal problems facing our valued clients. The Office deals in all kinds of civil, commercial and criminal cases and provides legal services in various fields and at all levels.",
        OurMission:"Our Mission",
        OurVision:"Our Vision",
        OurMissionBody: "we to provide exceptional legal guidance and support to our clients. We strive to offer personalized solutions, tailored to their unique needs and circumstances.  Our goal is not only to navigate legal complexities effectively but also to empower our clients with knowledge and confidence in their legal matters. With a commitment to integrity, professionalism, and client satisfaction, we aim to be a trusted partner in achieving our clients' legal objectives",
        OurVisionBody:"we to be the foremost destination for legal expertise and guidance, recognized for our unwavering commitment to excellence, innovation, and client satisfaction. We aspire to set new standards in the legal industry by fostering a culture of collaboration, integrity, and forward-thinking. Through our dedication to staying ahead of legal trends and advancements, we aim to empower individuals and businesses alike, ensuring they navigate legal challenges with confidence and clarity.",
        
        OurServicesT:"Our Services",
        OurServicesB:"We provide a wide range of legal services tailored to meet our clients needs.",
        OurServicesO:"Our goal is to provide reliable and effective legal support, empowering clients to navigate complex legal matters confidently.",
        
        english: 'English',
        arabic: 'عربي',

    },

    ar: {

        //header
        home: "الصفحة الرئيسية",
        service: 'خدماتنا',
        about: 'من نحن',
        contact: 'تواصل معنا',
        FreeLegalAdvice:'استشارة مجانا',

        // Service
        LegalConsultations:"الاستشارات القانونية",
        legalDocuments:"إعداد وصياغة الوثائق القانونية",
        LegalProcedures:"الإجراءات القانونية، تسجيل الاعتمادات القانونية",
        LegalRepresentation:"التمثيل القانوني",
        ResearchServices:"خدمات البحث",
        PenalCases:"قضايا جنائية",
        CriminalCases:"قضايا جنائية",
        CybercrimeLawsuit:"   الجرائم الإلكترونية",
        LaborLawsuit:"دعوى قانونية في مجال العمل",
        RentDisputes:"نزاعات الإيجار",
        FamilyIssuesAndConditions:"قضايا الأسرة والظروف",
        Insurance:"التأمين",
        MaritimeDisputes:"نزاعات بحرية",
        BankingAndFinance:"البنوك والتمويل",
        TradingCompanies:"شركات التجارة",
        LitigationAndDisputeResolution:"التقاضي وحل النزاعات",
        PrecautionaryMeasures:"التدابير الاحترازية",
        ExecutiveActions:"إجراءات تنفيذية",
        RealEstateDisputes:"نزاعات العقارات",
        DebtCollection:"تحصيل الديون",

        // Legal Consultations
        Saleh_Al_Saleh_Legal_Consultations:"صالح الصالح للمحاماة والاستشارات القانونية",
        SalehAlSalehLegalConsultationsB1:"تقدم مكتب صالح الصالح للمحاماة والاستشارات القانونية النصائح القانونية من خلال اختيار متميز من المستشارين القانونيين. يتميز المكتب بأنه يواكب التطورات والتقنيات الحديثة. في هذا العصر المتسارع، يحتاج كل إنسان إلى معرفة حقوقه وواجباته والموقف القانوني تجاه أمر أو مشروع يقدم له، بسرعة ودقة كبيرتين. لذلك، أخذنا عناية بهذا الأمر، ولم نقتصر على الطرق التقليدية للتواصل بين المكتب وعملائه الراغبين في الحصول على استشارة قانونية بشأن موضوع معين. تقليديًا، يجب على أي عميل يرغب في الحصول على استشارة قانونية الذهاب إلى مكتب متخصص في هذا الشأن. ولكن في مكتب صالح الصالح للمحاماة والاستشارات القانونية، هناك اختلاف، حيث يمكنك إرسال استشارة قانونية لنا عبر البريد الإلكتروني، مشرحًا جميع التفاصيل المتعلقة بها. سيقوم أحد المستشارين المتخصصين بالمكتب بالتشاور فيها وإعطاء رأيهم القانوني، بدعم من نصوص القانون، ثم إرسالها لك عبر البريد الإلكتروني أو الفاكس، مع مراعاة سرية جميع البيانات والمعلومات الواردة في الاستشارة.",
        Saleh_Al_Saleh_Legal_ConsultationsB2:"نظرًا لأن استشارات القانون تلعب دورًا مهمًا وفعّالًا في توجيه وإرشاد العملاء قبل بدء الإجراءات القانونية، فإن المكتب مهتم بتقديم أفضل الخدمات للعملاء من خلال خدمة الاستشارات القانونية التي تقدمها فريق متخصص. يقدم هذا الفريق الاستشارات القانونية من خلال مستشارين مؤهلين، يتمتعون بخبرة ومعرفة متخصصة وعلمية، وذلك من خلال أحدث التقنيات سواء عبر الهاتف أو الإنترنت أو البريد الإلكتروني أو الفاكس أو الرسائل النصية. تتطلب خدمة الاستشارات القانونية تقديم النصائح بسرعة لتمكين المستجيب من اتخاذ القرارات بسرعة ودقة.",
        Saleh_Al_Saleh_Legal_ConsultationsB3:"نقدم استشارات باللغتين العربية والإنجليزية في جميع الجوانب القانونية التي تلبي احتياجات الأفراد والشركات في حياتهم اليومية أو في مسائل الاستثمار والأعمال، من خلال تقديم النصائح القانونية والإرشاد حول الإجراء المناسب لحماية مصالح العميل في كل مشكلة، لضمان فهم العميل لمشكلته وتداعياتها والإجراءات التي يجب اتخاذها لحل المشكلة وتفادي العواقب الجسيمة.",
        Saleh_Al_Saleh_Legal_ConsultationsB4:"يقدم المكتب استشارات قانونية سواء من خلال ترتيب موعد للاجتماع مع المحامي المختص والمستشار القانوني المسؤول في المكتب، أو من خلال المراسلات الإلكترونية أو تأكيد الهاتف. يقدم المكتب الاستشارات القانونية بشكل مكتوب وتغطيها الحقوق القانونية، والممارسات القضائية، وتفسيرات الفقهاء للإشارة إلى الارتباط القوي وضمان عميل المكتب من صحة الاستشارة القانونية ودعمها.",
        Saleh_Al_Saleh_Legal_ConsultationsB5:"المكتب مرتبط بعدة عقود استشارية سنوية مع الشركات التجارية والمؤسسات المالية التي ترغب في تلقي خدمات مستمرة طوال العام سواء كانت بموجب عقد ثابت برسم سنوي أو عقود بعدد ثابت أو غير محدد من الساعات، أو بموجب عقود تعتمد على ساعات العمل للمستشارين والباحثين القانونيين والمحامين لضمان تنوع الخيارات للعملاء.",
        Saleh_Al_Saleh_Legal_ConsultationsB6:"يُعتبر مكتب صالح الصالح مصدرًا موثوقًا؛ لأن الاستشارات القانونية التي يصدرها دائمًا ما ترافقها دليل ومصدر وبيان شامل يكفي لفهم العميل في البداية، لضمان أنه يطمئن إلى صحة الأسس التي صدرت عليها الاستشارة القانونية.",
        Lookingforlegaladvice:"هل تبحث عن استشارة قانونية؟ اتصل بنا، وسنبدأ تعاونًا مثمرًا.",
        
        // Preparation and drafting of legal documents
         Preparation_legal_documentsB:"هو المكتب الأشهر في التحضير وصياغة القانون في الإمارات حيث يتوفر لدينا فريق متخصص من المستشارين القانونيين والباحثين ذوي الخبرة في التحضير وصياغة النسخ القانونية والوثائق من مختلف الأشكال والأنواع. يقدم المكتب خدمات التحضير والصياغة باللغتين العربية والإنجليزية. وتشمل هذه جميع تنفيذ الشركات والمؤسسات ذات المسؤولية المحدودة، والمساهمات الخاصة والعامة، وريادة الأعمال والأفراد كأمثلة على مثل هذه الخدمات نحو صياغة وتحرير",
         Preparation_legal_documents1:"مذكرة التأسيس ومرفقاتها",
        Preparation_legal_documents2:"عقد واتفاقية الاندماج والاستحواذ",
        Preparation_legal_documents3:"عقود وكالة تجارية",
        Preparation_legal_documents4:"اتفاقيات التحكيم",
        Preparation_legal_documents5:"عقود واتفاقيات رعاية التجارة",
        Preparation_legal_documents6:"عقود التوقيف والوصية",
        Preparation_legal_documents7:"عقد الرهن",
        Preparation_legal_documents8:"عقود الاعتماد",
        Preparation_legal_documents9:"عقود العمل",
        Preparation_legal_documents10:"اتفاقيات المصالحة",
        Preparation_legal_documents11:"عقود التسويق",
        Preparation_legal_documents12:"اتفاقية إدارة المؤثرين والتأثيرات",
        Preparation_legal_documents13:"مذكرات التفاهم",
        Preparation_legal_documents14:"محاضر التصفية",
        Preparation_legal_documents15:"محاضر الجلسات العامة",
        Preparation_legal_documents16:"قسم الشهادة",
        Preparation_legal_documents17:"خطاب تفويض",
        Preparation_legal_documents18:"لوائح الانضباط الداخلي",
        Preparation_legal_documents19:"مذكرة الرأي القانوني",
        Preparation_legal_documents20:"الشروط والأحكام التنظيمية",
        Preparation_legal_documents21:"صياغة مذكرة الرأي والمشورة القانونية",
        Preparation_legal_documents22:"المراسلات القانونية",
        Preparation_legal_documents23:"صياغة الشكاوى والاقتراحات",
        Preparation_legal_documents24:"كتابة المراسلات القانونية",
        Preparation_legal_documents25:"عقود واتفاقيات الشراكة",
        Preparation_legal_documents26:"عقد المساهمين",
        Preparation_legal_documents27:"اتفاقيات سرية المعلومات",
        Preparation_legal_documents28:"عقود العلامات التجارية",
        Preparation_legal_documents29:"عقود حقوق العقارات",
        Preparation_legal_documents30:"عقود القروض",
        Preparation_legal_documents31:"عقود الإعفاء",
        Preparation_legal_documents32:"عقود الإيجار",
        Preparation_legal_documents33:"اتفاقيات التسوية",
        Preparation_legal_documents34:"عقود المقاولات",
        Preparation_legal_documents35:"عقود خدمات اللوجستيات",
        Preparation_legal_documents36:"الشروط والأحكام",
        Preparation_legal_documents37:"محاضر الجلسات العادية والغير عادية للجمعيات العامة لجميع الشركات",
        Preparation_legal_documents38:"محضر الإفلاس",
        Preparation_legal_documents39:"محاضر الاجتماعات",
        Preparation_legal_documents40:"وكالة عامة وخاصة",
        Preparation_legal_documents41:"اللوائح التنظيمية ولوائح الشركات",
        Preparation_legal_documents42:"مذكرات قانونية مختلفة",
        Preparation_legal_documents43:"مراجعة الوثائق القانونية",
        Preparation_legal_documents44:"المراجعة والتحليل القانوني للعقود والاتفاقيات",
        Preparation_legal_documents45:"تحذيرات قانونية",
        Preparation_legal_documents46:"صياغة التحذيرات القانونية",
        Preparation_legal_documents47:"كتابة مذكرات قانونية متنوعة",

        //Legal procedures, registration and legal credits
        LegalProcedures:"الإجراءات القانونية والتسجيل والاعتمادات القانونية",
        LegalProceduresB:"تقدم الإجراءات القانونية والتسجيل والاعتمادات القانونية في دولة الإمارات العربية المتحدة حيث لدينا فريق متخصص من المحامين والمساعدين القانونيين ذوي الخبرة في إجراء الإجراءات في مختلف المجالات ومختلف الأعمال الحكومية والخاصة بما في ذلك كافة أعمال التنفيذ القانوني. ومن أمثلة هذه الخدمات ما يلي:",
        LegalProceduresB1:"تسجيل الشركات والمؤسسات ذات المسؤولية المحدودة.",
        LegalProceduresB2:"تسجيل الشركات وريادة الأعمال",
        LegalProceduresB3:"العلامات التجارية",
        LegalProceduresB4:"الإفلاس",
        LegalProceduresB5:"تسجيل الشركات المساهمة الخاصة والعامة",
        LegalProceduresB6:"تسجيل الملكية الفكرية",
        LegalProceduresB7:"التصفية",
        LegalProceduresB8:"الإفلاس",
        LegalProceduresB9:"- التغيير: يشمل تغيير اسم التجارة، تغيير النشاط، تغيير إدارة العناصر، تغيير رأس المال، تغيير مدة الشركة أو أي شروط أخرى في العقد، تغيير واحد أو أكثر من أهداف شراكة الخدمة مع الشركاء، التغيير الكبير في الهيكل التنظيمي للخدمة أو الشركاء يؤثر على إدارة ووضع الشراكة، تغيير في هيكل الخدمات المشتركة بين الخدمة والشركاء، تغيير واحد أو أكثر من أهداف شراكة الخدمة مع الشركاء في هيكلها التنظيمي أو الشركاء يؤثر على إدارة ووضع الشراكة المبرمة، مراجعة العقد الشراكة الحالي وتقديم تقرير إلى الإدارة العليا يشير إلى نطاق تغيير الشراكة للتفاوض مع الشركاء بشأن الأهداف أو الخدمات التي يتعين تغييرها أو إضافتها إلى عقد الشراكة، التعديل والتغيير وفقًا لجودة الخدمات المقدمة من خلال الشركاء لتعديل أو تعديل التشريعات الحكومية والقوانين بمخالفة لاتفاقيات الشراكة المبرمة مسبقًا؛ إعداد عقد الشراكة المعدل بالتنسيق مع إدارة الشؤون القانونية، توقيع عقد الشراكة المعدل وتغطية الحدث بشكل إعلامي إذا كان التعديل ذو أهمية ويؤثر على العملاء؛ إنشاء مجموعة مشتركة لتنفيذ أحكام الاتفاقية المعدلة، ومجموعة مشتركة لتنفيذ أحكام الاتفاقية المعدلة.",
        LegalProceduresB10:"حصر الموروثات",
        LegalProceduresB11:"إثبات القدرة العقلية والأهلية",
        LegalProceduresB12:"المعلومات الشخصية لولي الأمر (مدعمة بجواز سفره)",
        LegalProceduresB13:"ما إذا كانت الوصية الأخرى تتعلق بملك الموصي ومكان تسجيله وما إذا كانت ترغب في إلغائها",
        LegalProceduresB14:"تفاصيل الحساب البنكي",
        LegalProceduresB15:"إثبات الدين",
        LegalProceduresB16:"العناصر اللازمة لكتابة الوصية",
        LegalProceduresB17:"شجرة العائلة (أفراد الأسرة ومن يعولون ولي أمرهم)",
        LegalProceduresB18:"تفاصيل الملكية مدعومة بنسخ من سندات الملكية",
        LegalProceduresB19:"تفاصيل أي عقار آخر",
        
        // body
        Saleh_Al_Saleh: "صالح ال صالح للمحاماة و الاستشارات القانونية",
        body_index:"مكتب صالح الصالح للمحاماة والاستشارات القانونية هو واحد من أبرز مقدمي الخدمات القانونية في الإمارات العربية المتحدة من خلال الخبرة القانونية والطرق المهنية، مضمونًا رضى العملاء من المشاكل القانونية التي تواجهها. يتعامل المكتب في جميع أنواع القضايا المدنية والتجارية والجنائية ويقدم خدمات قانونية في مختلف المجالات وعلى جميع المستويات.",
        OurMission:"مهمتنا",
        OurVision:"رؤيتنا",
        OurMissionBody:"نحن نسعى لتقديم إرشاد قانوني استثنائي ودعم لعملائنا. نحن نسعى لتقديم حلول شخصية، مصممة لتلبية احتياجاتهم وظروفهم الفريدة. هدفنا ليس فقط توجيه العملاء عبر التعقيدات القانونية بفعالية، ولكن أيضًا تمكينهم بالمعرفة والثقة في شؤونهم القانونية. من خلال التزامنا بالنزاهة والاحترافية ورضا العملاء، نهدف إلى أن نكون شريكًا موثوقًا في تحقيق أهدافهم القانونية.",
        OurVisionBody:"نحن نسعى أن نكون الوجهة الرئيسية للخبرة القانونية والإرشاد، معترفين بالتزامنا الثابت بالتميز والابتكار ورضا العملاء. نطمح لوضع معايير جديدة في صناعة القانون من خلال تعزيز ثقافة التعاون والنزاهة والتفكير المستقبلي. من خلال التفاني للبقاء في صدارة الاتجاهات القانونية والتطورات، نهدف إلى تمكين الأفراد والشركات على حد سواء، مضمونين أنهم سيتخطون التحديات القانونية بثقة ووضوح.",

        OurServicesT:"خدماتنا",
        OurServicesB:"نحن نقدم مجموعة واسعة من الخدمات القانونية مصممة لتلبية احتياجات عملائنا.",
        OurServicesO:"هدفنا هو تقديم دعم قانوني موثوق وفعّال، يمكن العملاء من التنقل بثقة في المسائل القانونية المعقدة.",

        english: 'English',
        arabic: 'عربي',
    },
};


const languageSelector = document.querySelector('select');
languageSelector.addEventListener('change', (event) => {
    setLanguage(event.target.value);
    localStorage.setItem('lang',event.target.value)

});
document.addEventListener('DOMContentLoaded', () => {
   
    setLanguage(localStorage.getItem("lang"));
})
const setLanguage = (language) => {
    const elements = document.querySelectorAll("[data-i18n]");
    elements.forEach((element) =>{
        const translationsKey = element.getAttribute("data-i18n");
        element.textContent = translations[language][translationsKey];
    });
    document.dir = language == "ar" ? "rtl" :"ltr";
};